import type { Metadata } from "next";
import { Inter, Andada_Pro } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})
 
const andada = Andada_Pro({
  subsets:['latin'],
  variable: '--font-andada-pro',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${andada.variable}` }>{children}</body>
    </html>
  );
}
